Repository SouthbankSoftware/provendocs, pull requests merged in 2019-04, with the labels that each got.

#8 Update landing page for master branch (live website)
  src/client/components/Navigation/TopNavBar.jsx
  src/client/components/Pages/Landing.jsx
Labels: enhancement

#7 Home Page Updates.
  src/client/components/Navigation/TopNavBar.jsx
  src/client/components/Pages/HomePage.jsx
Labels: enhancement

#9 Mobile Friendly Landing Page
  src/client/components/Footer/Footer.scss
  src/client/components/Navigation/TopNavBar.scss
  src/client/components/Pages/Landing.scss
  src/client/style/global_styles.scss
Labels: enhancement

#10 Mobile friendly home page.
  src/client/components/Footer/Footer.scss
  src/client/components/Navigation/TopNavBar.scss
  src/client/components/Pages/HomePage.scss
  src/client/style/global_styles.scss
Labels: enhancement

#14 Bugfix/shared document preview broken
  src/client/common/constants.js
  src/client/components/Dashboard/ViewFiles.scss
  src/client/components/Navigation/TopNavBar.jsx
  src/client/components/Pages/Dashboard.jsx
  src/client/components/Pages/SharedDocument.jsx
  src/client/components/Pages/SharedDocument.scss
  src/client/components/Pages/Status/404.scss
  src/client/components/Pages/Status/503.scss
  src/client/components/ViewDocument/ViewDocument.scss
  src/client/style/icons/pages/top-nav-bar/house-icon.svg
  src/server/helpers/archiveBuilder.js
Labels: bug

#15 Feature/update policy
  src/client/components/Navigation/TopNavBar.jsx
  src/client/components/Navigation/TopNavBar.scss
  src/client/components/Pages/Dashboard.jsx
  src/client/components/Pages/Landing.scss
  src/client/components/Privacy/EULA.md
  src/client/components/Privacy/Policy.md
  src/client/components/Privacy/Security_Measures.md
  src/client/style/global_styles.scss
Labels: enhancement

#16 Feature/ux updates
  README.md
  package.json
  src/client/common/landing_content.js
  src/client/components/Common/Error.jsx
  src/client/components/Common/Loading.jsx
  src/client/components/Dashboard/NewFileUpload.jsx
  src/client/components/Dashboard/ProofComplete.jsx
  src/client/components/Dashboard/ProofComplete.scss
  src/client/components/Dashboard/ProofInProgress.jsx
  src/client/components/Dashboard/ProofInProgress.scss
  src/client/components/Dashboard/TabbedPanel.scss
  src/client/components/Dashboard/ViewFiles.jsx
  src/client/components/Dashboard/ViewFiles.scss
  src/client/components/Footer/Footer.jsx
  src/client/components/Login/EmailLogin.jsx
  src/client/components/Navigation/TopNavBar.jsx
  src/client/components/Pages/Dashboard.jsx
  src/client/components/Pages/Dashboard.scss
  src/client/components/Pages/HomePage.jsx
  src/client/components/Pages/HomePage.scss
  src/client/components/Pages/Landing.scss
  src/client/components/ViewDocument/ViewDocument.jsx
  src/client/components/ViewDocument/ViewDocument.scss
  src/client/components/index.js
  src/server/helpers/sendgrid.js
  yarn.lock
Labels: enhancement

#17 Added Env Variable for Driver Pool Size.
  src/server/helpers/mongoAPI.js
Labels: enhancement

#18 Bugfix/ux and stability
  src/client/components/Dashboard/ProofInProgress.jsx
  src/client/components/Dashboard/ViewFiles.jsx
  src/client/components/Navigation/TopNavBar.jsx
  src/client/components/Navigation/TopNavBar.scss
  src/client/components/Pages/Dashboard.jsx
  src/client/components/Pages/HomePage.jsx
  src/client/components/Pages/Landing.jsx
  src/client/components/ViewDocument/ViewDocument.jsx
  src/client/components/ViewDocument/ViewDocument.scss
  src/server/helpers/archiveBuilder.js
  src/server/helpers/mongoAPI.js
  src/server/pages/failedToGetArchive.html
  src/server/routes/utilRoutes.js
Labels: enhancement

#22 Bugfix/excel preview infinite load
  src/client/components/ExcelPreview/ExcelPreview.jsx
  src/client/components/ViewDocument/ViewDocument.jsx
  src/client/components/ViewProof/ProofDiagram.jsx
  src/client/components/ViewProof/ViewProof.jsx
  src/client/components/ViewProof/ViewProofCertificate.jsx
Labels: bug

#24 Feature/user testing feedback
  src/client/components/Dashboard/CommentAndTags.jsx
  src/client/components/Dashboard/EmailProofButton.jsx
  src/client/components/Dashboard/ProofComplete.jsx
  src/client/components/Dashboard/ProofInProgress.jsx
  src/client/components/Navigation/TopNavBar.jsx
  src/client/components/Pages/Dashboard.jsx
  src/client/components/Pages/SharedDocument.jsx
  src/client/components/Pages/SharedDocument.scss
  src/client/components/ShareDialog/ShareDialog.jsx
  src/client/components/ShareDialog/ShareDialog.scss
  src/client/components/ViewDocument/ViewDocument.jsx
  src/client/components/ViewDocument/ViewDocument.scss
  src/server/helpers/mongoAPI.js
  src/server/routes/shareRoutes.js
Labels: bug, enhancement

#27 Fix/display scaling
  src/client/common/api.js
  src/client/components/Dashboard/ViewFiles.jsx
  src/client/components/Dashboard/ViewFiles.scss
  src/client/components/Navigation/TopNavBar.jsx
  src/client/components/Navigation/TopNavBar.scss
  src/client/components/Pages/Dashboard.jsx
  src/client/components/Pages/Dashboard.scss
  src/client/style/global_styles.scss
  src/server/helpers/workers/createCertificateWorker.js
  src/server/routes/utilRoutes.js
Labels: enhancement

#28 Feature/landing page animation
  src/client/components/Dashboard/TabbedPanel.scss
  src/client/components/Dashboard/ViewFileThumb.jsx
  src/client/components/Dashboard/ViewFiles.jsx
  src/client/components/Dashboard/ViewFiles.scss
  src/client/components/Navigation/TopNavBar.scss
  src/client/components/Pages/Dashboard.scss
  src/client/components/Pages/HomePage.jsx
  src/client/components/Pages/HomePage.scss
  src/client/style/global_styles.scss
  src/client/style/icons/pages/dashboard/mail-icon.svg
  src/client/style/icons/pages/landing-page/monitor-vector.svg
  src/client/style/icons/pages/landing-page/proven-docs-animation.gif
  src/client/style/icons/pages/login-signup-pages/google-icon.svg
Labels: bug, enhancement

#29 Feature/delete account
  README.md
  src/client/components/Dashboard/ViewFiles.scss
  src/client/components/Navigation/TopNavBar.jsx
  src/client/components/Pages/Dashboard.jsx
  src/client/routes/routes.jsx
  src/server/helpers/mongoAPI.js
  src/server/routes/utilRoutes.js
Labels: enhancement

#30 Feature/downloads page
  .gitignore
  docs/provendb-litepaper.pdf
  src/client/common/constants.js
  src/client/components/Navigation/TopNavBar.jsx
  src/client/components/Pages/Downloads.jsx
  src/client/components/Pages/DownloadsPage.scss
  src/client/components/Pages/index.js
  src/client/routes/routes.jsx
  src/client/style/global_styles.scss
Labels: enhancement

#32 Updated the litepaper
  docs/provendb-litepaper.pdf
Labels: enhancement

#36 Minor Linting Fix.
  src/client/components/Pages/Dashboard.jsx
Labels: bug

#37 Feature/refferal system
  package.json
  src/client/common/api.js
  src/client/components/Dashboard/ViewFileThumb.jsx
  src/client/components/ExcelPreview/ExcelPreview.jsx
  src/client/components/Navigation/TopNavBar.scss
  src/client/components/Pages/Dashboard.jsx
  src/client/components/Pages/Downloads.jsx
  src/client/components/Pages/HomePage.jsx
  src/client/components/Pages/LoginSignup.scss
  src/client/components/Pages/RegistrationPage.jsx
  src/client/components/Register/EnterReferralCode.jsx
  src/client/components/Register/index.js
  src/client/components/ShareDialog/ShareDialog.jsx
  src/client/components/ViewProof/ProofDiagram.jsx
  src/client/index.jsx
  src/client/style/global_styles.scss
  src/client/templates/index.ejs
  src/server/common/constants.js
  src/server/helpers/archiveBuilder.js
  src/server/helpers/certificateBuilder.js
  src/server/helpers/growsurfHelpers.js
  src/server/helpers/mongoAPI.js
  src/server/routes/fileRoutes.js
  src/server/routes/shareRoutes.js
  src/server/routes/utilRoutes.js
  yarn.lock
Labels: bug, enhancement

#38 Minor linting fix caused from auto-merge.
  src/client/components/Pages/Dashboard.jsx
Labels: bug

#39 Growsurf ID post-build injection.
  package.json
  src/client/App.jsx
  src/client/components/Pages/RegistrationPage.jsx
  src/client/templates/index.ejs
  yarn.lock
Labels: bug

#40 Env Variable for PROVENDOCS_ENV is now fetched from the back end server.
  src/client/App.jsx
  src/client/common/api.js
  src/client/common/constants.js
  src/client/components/Pages/Dashboard.jsx
  src/client/components/Pages/Downloads.jsx
  src/client/components/ShareDialog/ShareDialog.jsx
  src/client/components/ViewProof/ProofDiagram.jsx
  src/client/index.jsx
  src/server/routes/authRoutes.js
Labels: bug

#41 Fix/ux fixes
  src/client/common/constants.js
  src/client/components/Dashboard/NewFileUpload.jsx
  src/client/components/ViewDocument/ViewDocument.jsx
  src/server/helpers/fileHelpers.js
  src/server/helpers/mongoAPI.js
  src/server/helpers/userHelpers.js
  src/server/routes/fileRoutes.js
  src/server/routes/shareRoutes.js
Labels: bug

#42 Fix/dev env fixes
  src/client/common/api.js
  src/client/components/Dashboard/NewFileUpload.jsx
  src/client/components/Dashboard/ViewFiles.jsx
  src/client/components/Dashboard/ViewFiles.scss
  src/client/components/ViewProof/ProofDiagram.jsx
  src/client/components/ViewProof/ViewProof.jsx
  src/client/style/global_styles.scss
  src/server/helpers/archiveBuilder.js
  src/server/helpers/mongoAPI.js
  src/server/routes/fileRoutes.js
  src/server/routes/uploadRoutes.js
Labels: bug, enhancement

#43 Fixed bug with archive README date.
  src/server/helpers/archiveBuilder.js
Labels: bug

#48 Fix/cross browser styling
  ENVIRONMENT_VARIABLES.md
  src/client/App.jsx
  src/client/common/api.js
  src/client/components/Dashboard/ViewFiles.scss
  src/client/components/Pages/Dashboard.jsx
  src/client/components/Pages/DownloadsPage.scss
  src/client/components/Pages/HomePage.scss
  src/client/components/Pages/SharedDocument.scss
  src/client/components/ShareDialog/ShareDialog.jsx
  src/client/components/ViewDocument/ViewDocument.scss
  src/client/components/ViewProof/ProofDiagram.jsx
  src/client/components/ViewProof/ProofDiagram.scss
  src/client/components/ViewProof/ViewProof.scss
  src/client/style/global_styles.scss
  src/server/helpers/archiveBuilder.js
  src/server/helpers/certificateBuilder.js
  src/server/helpers/growsurfHelpers.js
  src/server/routes/shareRoutes.js
  src/server/routes/utilRoutes.js
  src/server/server.js
Labels: bug, enhancement

#49 - Use Crypt Key for growsurf secret.
  src/client/components/Dashboard/NewFileUpload.jsx
  src/server/helpers/fileHelpers.js
  src/server/helpers/growsurfHelpers.js
  src/server/routes/shareRoutes.js
  src/server/server.js
Labels: bug

#51 Fix/update support links
  README.md
  RELEASE_NOTES.md
  src/client/components/Pages/HomePage.jsx
  src/client/components/Pages/Landing.jsx
  src/server/helpers/certificates/README.md
  src/server/helpers/workers/createCertificateWorker.js
Labels: enhancement

#52 Fix/build fix
  src/client/components/Pages/HomePage.jsx
  src/client/components/Pages/RegistrationPage.jsx
Labels: bug

#53 Minor pre-launch changes.
  src/client/components/Footer/Footer.jsx
  src/client/components/Pages/HomePage.jsx
  src/client/components/Pages/Landing.jsx
  src/client/components/Pages/RegistrationPage.jsx
Labels: bug

#56 Fix/forget doesnt update usage
  src/client/components/Dashboard/ViewFiles.jsx
  src/client/components/Pages/Dashboard.jsx
  src/client/components/Pages/HomePage.jsx
  src/client/components/Pages/RegistrationPage.jsx
Labels: bug
